config/routes.rb
Rails.application.routes.draw do
  #検索
  get "search" => "searches#search", as: "search"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  #devise関連
  devise_for :users

  #ホーム系
  root :to =>"homes#top"
  get "home/about"=>"homes#about"

  #書籍関連
  resources :books, only: [:index,:show,:edit,:create,:destroy,:update] do
    resources :book_comments, only: [:create, :destroy]
    resource :favorite, only: [:create, :destroy]
  end

  #ユーザー関連
  resources :users, only: [:index,:show,:edit,:update] do
    resource :relationship, only: [:create, :destroy]
    get "search" => "users#search"

    member do
      get :followings
      get :followers
    end
  end


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book

  validates :user_id, uniqueness: {scope: :book_id}

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    @book = Book.find(params[:book_id])
    favorite = current_user.favorites.new(book_id: @book.id)
    favorite.save
    respond_to do |format|
      format.js
    end
  end

  def destroy
    @book = Book.find(params[:book_id])
    favorite = current_user.favorites.find_by(book_id: @book.id)
    favorite.destroy
    respond_to do |format|
      format.js
    end
  end
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/views/favorites/_favorite-btn.html.erb
<div id="favorite-btn-<%= book.id %>">
  <% if book.favorited_by?(current_user) %>
    <%= link_to book_favorite_path(book), method: :delete, remote: true do %>
      <i class="fa-solid fa-heart" style="color: red;"></i><%= book.favorites.count %>
    <% end %>              
  <% else %>
    <%= link_to book_favorite_path(book), method: :post, remote: true do %>
      <i class="fa-solid fa-heart"></i><%= book.favorites.count %>
    <% end %>
  <% end %>
</div>

app/views/favorites/create.js.erb
$("#favorite-btn-<%= @book.id %>").html("<%= j(render partial: 'favorites/favorite-btn', locals: { book: @book }) %>");

app/views/favorites/destroy.js.erb
$("#favorite-btn-<%= @book.id %>").html("<%= j(render partial: 'favorites/favorite-btn', locals: { book: @book }) %>");