config/routes.rb
Rails.application.routes.draw do
  #検索
  get "search" => "searches#search", as: "search"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  #devise関連
  devise_for :users

  #ホーム系
  root :to =>"homes#top"
  get "home/about"=>"homes#about"

  #書籍関連
  resources :books, only: [:index,:show,:edit,:create,:destroy,:update] do
    resources :book_comments, only: [:create, :destroy]
    resource :favorite, only: [:create, :destroy]
  end

  #ユーザー関連
  resources :users, only: [:index,:show,:edit,:update] do
    resource :relationship, only: [:create, :destroy]
    get "search" => "users#search"

    member do
      get :followings
      get :followers
    end
  end


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :followings, through: :relationships, source: :followed
  has_many :reverse_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :followers, through: :reverse_relationships, source: :follower
  has_one_attached :profile_image

  validates :name, length: { minimum: 2, maximum: 20 }, uniqueness: true
  validates :introduction, length: { maximum: 50 }

  
  
  def get_profile_image
    (profile_image.attached?) ? profile_image : 'no_image.jpg'
  end

  def following?(user)
    followings.exists?(id: user.id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :ensure_correct_user, only: [:edit, :update, :destroy]

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
    @today_book = @books.created_today
    @yesterday_book = @books.created_yesterday
    @this_week_book = @books.created_this_week
    @last_week_book = @books.created_last_week

    @daily_counts = (6.day.ago.to_date..Date.today).map do |date|
      label = case date
        when Date.today then #今日
        when 1.day.ago.to_date then #1日前
        when 2.day.ago.to_date then
        when 3.day.ago.to_date then
        when 4.day.ago.to_date then
        when 5.day.ago.to_date then
        when 6.day.ago.to_date then
        end
      {
        date: label,
        count: @user.books.where(created_at: date.beginning_of_day..date.end_of_day).count
      }
    end

  end

  def index
    @users = User.all
    @book = Book.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user.id), notice: "You have updated user successfully."
    else
      render :edit
    end
  end

  def followings
    @user = User.find(params[:id])
    @users = @user.followings
  end

  def followers
    @user = User.find(params[:id])
    @users = @user.followers
  end

  def search
    @user = User.find(params[:user_id])
    @books = @user.books
    @book = Book.new
    if params[:created_at] == ""
      @search_book = "日付を選択して下さい"
    else
      created_at = params[:created_at]
      @search_book = @books.where(['created_at LIKE ? ', "#{created_at}%"]).count
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

  def ensure_correct_user
    user = User.find(params[:id])
    unless user == current_user
      redirect_to user_path(current_user)
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_index.html.erb
<table class='table'>
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% users.each do |user| %>
      <tr>
        <td><%= image_tag user.get_profile_image, size: '50x50' %></td>
        <td><%= user.name %></td>
        <% if user == current_user || current_user.following?(user) %>
          <td>フォロー数：<%= user.followings.count %></td>
          <td>フォロワー数：<%= user.followers.count %></td>
          <% if user != current_user %>
            <td>
              <%= link_to "フォロー外す", user_relationship_path(user), method: :delete %>
            </td>
          <% end %>
        <% else %>
          <td>
            <%= link_to "フォローする", user_relationship_path(user), method: :post %>
          </td>
        <% end %>
        <td><%= link_to 'Show', user %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/_info.html.erb
<table class='table'>
  <tr><%= image_tag user.get_profile_image, size:'100x100' %></tr>
  <tr>
	  <th>name</th>
	  <th><%= user.name %></th>
  </tr>
  <tr>
	  <th>introduction</th>
	  <th><%= user.introduction %></th>
  </tr>
  <tr>
    <th>follows</th>
    <th><%= link_to "#{user.followings.count}", followings_user_path(user) %></th>
  </tr>
  <tr>
    <th>followers</th>
    <th><%= link_to "#{user.followers.count}", followers_user_path(user) %></th>
  </tr>
</table>
　
<% if user == current_user %>
  <div class='row'>
    <%= link_to edit_user_path(current_user), class: "btn btn-outline-secondary btn-block" do %>
      <i class="fas fa-user-cog"></i>
    <% end %>
  </div>
<% else %>
  <% if current_user.following?(user) %>
    <%= button_to "フォロー外す", user_relationship_path(user), method: :delete, class: "btn btn-danger btn-block" %>
  <% else %>
    <%= button_to "フォローする", user_relationship_path(user), method: :post, class: "btn btn-primary btn-block" %>
  <% end %>
<% end %>

app/views/users/_post_chart.html.erb
<canvas id="booksChart"></canvas>

<script>
  $(document).on('turbolinks:load', function() {
    var ctx = document.getElementById("booksChart");
    var booksChart = new Chart(ctx, {
      type: 'line',
      data: {
        labels: ['6日前', '5日前', '4日前', '3日前', '2日前', '1日前', '今日'],
        datasets: [
          {
            label: '投稿した本の数',
            data: [
              <%= @books.created_6day_ago.count %>,
              <%= @books.created_5day_ago.count %>,
              <%= @books.created_4day_ago.count %>,
              <%= @books.created_3day_ago.count %>,
              <%= @books.created_2day_ago.count %>,
              <%= @books.created_yesterday.count %>,
              <%= @books.created_today.count %>
            ],
            borderColor: 'blue',
            tension: 0.4,
            BackgroundColor: 'rgba(0,0,0,0)'
          }
        ],
      },
      options: {
        title: {
          display: true,
          text: '7日間の投稿数の比較'
        },
        responsive: true,
        scales: {
          y: {
            suggestedMin: 0,
            suggestedMax: 10
          },
        },
      } 
    });
  });
</script>

app/views/users/_post_search.html.erb
<h4>検索結果</h4>
<table class="table">
  <thead>
    <tr>
      <th>投稿数</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><%= search_book %></td>
    </tr>
  </tbody>
</table>

app/views/users/_post_statistics.html.erb
<h2 class="mt-5 mb-4">投稿数の前日比・前週比</h2>

<div class="row">
  <div class="col-md-6">
    <table class="table table-bordered text-center">
      <thead class="table-light">
        <tr>
          <th>今日の投稿数</th>
          <th>前日の投稿数</th>
          <th>前日比</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td><%= @today_book.count %></td>
          <td><%= @yesterday_book.count %></td>
          <td>
            <% if @yesterday_book.count == 0 %>
              前日の投稿が0のため計算できません
            <% else %>
              <% @the_day_before = @today_book.count / @yesterday_book.count.to_f %>
              <%= (@the_day_before * 100).round %>%
            <% end %>
          </td>
        </tr>
      </tbody>
    </table>
  </div>

  <div class="col-md-6">
    <table class="table table-bordered text-center">
      <thead class="table-light">
        <tr>
          <th>今週の投稿数</th>
          <th>先週の投稿数</th>
          <th>前週比</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td><%= @this_week_book.count %></td>
          <td><%= @last_week_book.count %></td>
          <td>>
            <% if @last_week_book == 0 %>
              前週の投稿が0のため計算できません
            <% else %>
              <% @the_week_before = @this_week_book.count / @last_week_book.count.to_f %>
              <%= (@the_week_before * 100).round %>%
            <% end %>
          </td>
        </tr>
      </tbody>
    </table>
  </div>
</div>
  

app/views/users/_userlist.html.erb
<table class='table'>
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= image_tag user.get_profile_image, size: '50x50' %></td>
        <td><%= user.name %></td>
        <td>フォロー数：<%= user.followings.count %></td>
        <td>フォロワー数：<%= user.followers.count %></td>
        <td><%= link_to "Show", user %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/_weekly_post.html.erb
<h2 class="mt-5 mb-4">７日間分の投稿数</h2>

<div class="row">
  <div class="col-md-6">
    <table class="table table-bordered text-center">
      <thead class="table-light">
        <tr>
          <th>6日前</th>
          <th>5日前</th>
          <th>4日前</th>
          <th>3日前</th>
          <th>2日前</th>
          <th>1日前</th>
          <th>今日</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td><%= @books.created_6day_ago.count %></td>
          <td><%= @books.created_5day_ago.count %></td>
          <td><%= @books.created_4day_ago.count %></td>
          <td><%= @books.created_3day_ago.count %></td>
          <td><%= @books.created_2day_ago.count %></td>
          <td><%= @books.created_yesterday.count %></td>
          <td><%= @books.created_today.count %></td>
        </tr>
      </tbody>
    </table>
  </div>
</div>

app/views/users/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <h2>User info</h2>
    <%= form_with model:@user, local:true do |f| %>
      <%= render 'layouts/errors', obj: @user %>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control name" %>
      </div>
     <div class="form-group">
        <%= f.label :image %>
        <%= f.file_field :profile_image, class: "form-control-file user_image", accept: 'image/*' %>
      </div>
      <div class="form-group">
        <%= f.label :introduction %>
        <%= f.text_area :introduction, class: "form-control introduction" %>
      </div>
      <div class="form-group">
        <%= f.submit class: 'btn btn-secondary' %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/followers.html.erb
<h2>Follower Users</h2>
<% if @users.empty? %>
  <p>ユーザーはいません</p>
<% else %>
  <%= render partial: "userlist", locals: {users: @users} %>
<% end %>

app/views/users/followings.html.erb
<h2>Follow Users</h2>
<% if @users.empty? %>
  <p>ユーザーはいません</p>
<% else %>
  <%= render partial: "userlist", locals: {users: @users} %>
<% end %>

app/views/users/index.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info', user: current_user %>

      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Users</h2>
      <%= render 'index',users: @users %>
    </div>
  </div>
</div>

app/views/users/search.js.erb
$('#search_result').html("<%= j(render 'post_search', search_book: @search_book) %>");

app/views/users/show.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'info', user: @user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
      <%= render 'books/index',books: @books %>

      <%= form_with url:user_search_path(@user), method: :get, local: false do |f| %>
        <%= f.date_field :created_at %>
        <%= f.submit '検索', class: "btn btn-primary" %>
      <% end %>

      <div id="search_result">
        <% if @search_book.present? %>
          <%= render 'post_search', search_book: @search_book %>
        <% end %>
      </div>

      <%= render 'post_statistics', user: @user %>

      <%= render 'weekly_post', user: @user %>

      <%= render 'post_chart', user: @user %>
    </div>
  </div>
</div>